// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator
#if JSON_DB
using Newtonsoft.Json;

namespace ZIP.DLMS.Spodes
{

    public class SpodesUnits
    {

        [JsonProperty("id")]
        public int id { get; set; }

        [JsonProperty("name")]
        public string name { get; set; }

        [JsonProperty("unitType")]
        public string unitType { get; set; }

        [JsonProperty("comment")]
        public string comment { get; set; }

        [JsonProperty("abbrev")]
        public string abbrev { get; set; }

        [JsonProperty("okeiId")]
        [JsonIgnore]
        public object okeiId { get; set; }
    }

}
#endif
