// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator
#if JSON_DB

using Newtonsoft.Json;

namespace ZIP.DLMS.Spodes
{
    public class Spodes
    {

        [JsonProperty("ID")]
        public int ID { get; set; }

        [JsonProperty("ParentID")]
        public int? ParentID { get; set; }

        [JsonProperty("OrderID")]
        public double OrderID { get; set; }

        [JsonProperty("OBIS")]
        public string OBIS { get; set; }

        [JsonProperty("DescRU")]
        public string DescRU { get; set; }

        [JsonProperty("DescEN")]
        public string DescEN { get; set; }

        [JsonProperty("IIC")]
        public int? IIC { get; set; }

        [JsonProperty("Attr")]
        public string Attr { get; set; }

        [JsonProperty("MeterClasses")]
        public int? MeterClasses { get; set; }

        [JsonProperty("OKEI_ID")]
        public int? OKEI_ID { get; set; }

        [JsonProperty("Comment")]
        public string Comment { get; set; }

        [JsonProperty("ObjectType")]
        public int ObjectType { get; set; }

        [JsonProperty("Visibility")]
        public int Visibility { get; set; }

        [JsonProperty("Оbligatory")]
        public bool? Оbligatory { get; set; }

    }
}
#endif
